### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by doriath** [beancount/beanprice#25]
I see there is a `.travis.yml` file, but I believe travis is not actually running tests / lints on this project. Could we set it up, to ensure that all PRs do not break the code?

**Comment by dnicolodi** [comment]
We switched to Github actions for other repositories in under the beancount umbrella. It would make sense to do the same for this one. Feel free to have a look at what is done in the `beancount` or `beangulp` repos and propose a PR to implement the same.

**Comment by doriath** [comment]
Good to know, thanks! I will work on PR to remove Travis config and setup simple Github action to run tests and lint.

Should I try to setup some type checker as well, e.g. mypy or pytype?

**Comment by dnicolodi** [comment]
> Should I try to setup some type checker as well, e.g. mypy or pytype?

I don't see why not. There has been talk about doing it for other projects in the beancount umbrella, but I think only fava has extensive typing and I don't know if they run a checker as part of their CI.
