### ISSUE TITLE
Setup type checker in CI

### ISSUE THREAD

**Issue by doriath** [beancount/beanprice#31]
Track fixing existing issues and setting up type checker in CI.

I will use pytype as suggested in https://beancount.github.io/docs/beancount_v3_dependencies.html

**Comment by doriath** [comment]
Note: I think fava uses `mypy` instead of `pytest`.

Please let me know if you have any preferences for one or the other.

**Comment by dnicolodi** [comment]
I don't understand, mypy is a tipe checker, pytest is a unit test runner. What is the relation?

**Comment by doriath** [comment]
Sorry, I meant `pytype`, updated my comments.

**Comment by dnicolodi** [comment]
I think the Python world is converging toward mypy. The last time we spoke about this, the consensus was to use mypy, IIRC. @blais comment in the linked document is probably outdated.

**Comment by blais** [comment]
I think we should have all of them!
Pytype is not going away though, google is using it a ton

**Comment by xuhcc** [comment]
Implemented in #34. Thanks @doriath !
