### ISSUE TITLE
Should we use beanprice v2 or v3

### ISSUE THREAD

**Issue by doriath** [beancount/beanprice#36]
First, I am sorry for using issues to start a discussion (what do you think about enabling Github Discussions to have a place where questions related to beanprice development can be asked?).

Coming back to the question. AFAICT beanprice has been extracted from beancount v3 repo (beancount v2 still has bean-price binary), but beanprice repo depends on beancount v2. This means that when someone install beanprice, there is a conflict between the two binaries (I am actually not sure which bean-price is installed at that point, and it might be confusing to the user).

I was wondering if we should switch beanprice repo to use beancount v3 instead. What do you think?

**Comment by xuhcc** [comment]
beanprice works with both major beancount versions. I think that `beanprice` setup script shouldn't try to install beancount automatically but assume that it is already installed.

>This means that when someone install beanprice, there is a conflict between the two binaries (I am actually not sure which bean-price is installed at that point, and it might be confusing to the user).

One way to resolve this issue is to choose a different name for a `bean-price` binary. On my machine I renamed it to `bean-price-standalone`. We can also install it as `beanprice` (simply remove a hyphen).

**Comment by doriath** [comment]
I believe it does not work with v3 at head.

https://github.com/beancount/beanprice/blob/master/beanprice/price.py#L667

It uses `version.ArgumentParser`, but it no longer exists in `beancount.parser.version` module:

https://github.com/beancount/beancount/blob/master/beancount/parser/version.py

If we decide that beanprice should work with both v2 and v3, then we should fix the existing code to work with v3, and then write tests in the CI to verify that both are working.

**Comment by xuhcc** [comment]
>It uses version.ArgumentParser, but it no longer exists in beancount.parser.version module

I think we can replace it with `argparse.ArgumentParser`.

>If we decide that beanprice should work with both v2 and v3, then we should fix the existing code to work with v3, and then write tests in the CI to verify that both are working.

beanprice is intended to work with both v2 and v3, but v3 is still WIP so things can break from time to time. Running CI tests with both beancount versions seems to be a good idea.

**Comment by bayesianmind** [comment]
I fixed the current breakage in #41

**Comment by doriath** [comment]
Thank you Ben! We now have CI running both v2 and v3 versions - I think we can close this issue now.
