### ISSUE TITLE
Can't fetch from Google

### ISSUE THREAD

**Issue by ratsclub** [beancount/beanprice#47]
Running the command `bean-price -e USD:google/NASDAQ:FB` outputs the value below:
```
$ bean-price -e USD:google/NASDAQ:FB
ERROR   : Could not fetch for job: DatedPrice(base='NASDAQ:FB', quote='USD', date=None, sources=[PriceSource(module=<module 'google' (namespace)>, symbol='NASDAQ:FB', invert=False)])
```

**Comment by tarioch** [comment]
I think this price source doesn't exist anymore (at least looking at the source). I think it's no longer possible to fetch prices from google, so you will have to switch to one of the others.

**Comment by ratsclub** [comment]
I see. Thanks!
