### ISSUE TITLE
YahooError: Status 401: Invalid Cookie

### ISSUE THREAD

**Issue by maxromanovsky** [beancount/beanprice#75]
Yesterday I started getting the following error when trying to use `bean-price`:
```
ERROR   : Error fetching EURUSD=X: Status 401: {'code': 'Unauthorized', 'description': 'Invalid Cookie'}
```

Command line:
```
bean-price --no-cache --clobber --inactive budget.beancount >> prices.beancount
```

When I remove `--no-cache`, the issue is almost gone, but not always.
I suppose it's related with rate limiting or other measures on Yahoo side.

**Comment by collowe** [comment]
Getting the same error - even with a basic

```shell
bean-price -e 'USD:yahoo/AAPL'

**Comment by haomingw** [comment]
+1

**Comment by rizaon** [comment]
Specifying datetime let my query pass
```
bean-price -d 2023-04-19T18:00:00 -e USD:yahoo/AAPL
```

**Comment by collowe** [comment]
Back working again for me  :)

**Comment by redstreet** [comment]
> Specifying datetime let my query pass
> 
> ```
> bean-price -d 2023-04-19T18:00:00 -e USD:yahoo/AAPL
> ```

Thanks for this! Same issue as the OP. It works for me only if I specify a date (time is optional).

**Comment by maxromanovsky** [comment]
Here's what worked for me:
```sh
bean-price -d `date -u +%Y-%m-%dT%H:%M:%S` --no-cache --clobber --inactive budget.beancount >> prices.beancount
```

**Comment by ileodo** [comment]
will there be a fix for this? do we really need to write a bash script (by using -d) to back fill the historical prices?

**Comment by ileodo** [comment]
is this repo still under maintain?
