### ISSUE TITLE
ratesapi source no longer works

### ISSUE THREAD

**Issue by mrlimacz** [beancount/beanprice#80]
Looks like [exchangerate.host](https://exchangerate.host/) no longer works - they require an API key now and also a the response structure changed. I think it's a similar thing that happened to ratesapi.io back in 2021. Anybody knows an alternative?

**Comment by tarioch** [comment]
The alphavantage one works, but requires a free api key. e.g. CHF:alphavantage/fx:USD:CHF

**Comment by mrlimacz** [comment]
#82 

I went ahead and implemented a source that fetches directly from ECB data
